# Site settings
author: Matt Kuras
title: CuriousCoder
header-img: img/home-bg.png
email: mattkuras@gmail.com
copyright_name: Matt Kuras
description: > # this means to ignore newlines until "baseurl:"
  Wondering where I am
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: 
github_username:  mattkuras

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
